-- Drift-reconciliation migration: FK DROP+re-ADD (with updated ON DELETE semantics),
-- index DROP/re-CREATE, and column DEFAULT alignment.
--
-- Generated by drizzle-kit to reconcile the tracked schema with a drifted dev
-- database.  Only statements that change the schema relative to a clean
-- migration replay (0000→0136) are included — statements that would fail on a
-- fresh chain (duplicate ADD CONSTRAINT, DROP of non-existent objects) have
-- been excluded or wrapped in idempotent DO blocks.
--
-- The dropped memory_records indexes are re-created in 0141_restore_memory_indexes.
-- IF EXISTS / IF NOT EXISTS guards make this migration safe to re-run when
-- the migration tracker was not updated after the first successful application.
--> statement-breakpoint

-- ── Drop plan_review_gates status check constraint ──────────────────────
-- The schema no longer constrains plan_review_gates.status to a fixed set
-- of values (the check was removed from the drizzle definition).
ALTER TABLE "plan_review_gates" DROP CONSTRAINT IF EXISTS "plan_review_gates_status_check";
--> statement-breakpoint

-- ── Drop FK constraints whose ON DELETE semantics have changed ──────────
-- These are re-added below with the updated semantics (no action → cascade
-- for plugin tables, short names → long fully-qualified names for
-- environment custom image tables).
ALTER TABLE "document_revisions" DROP CONSTRAINT IF EXISTS "document_revisions_company_id_companies_id_fk";
--> statement-breakpoint
ALTER TABLE "documents" DROP CONSTRAINT IF EXISTS "documents_company_id_companies_id_fk";
--> statement-breakpoint
ALTER TABLE "plugin_entities" DROP CONSTRAINT IF EXISTS "plugin_entities_company_id_companies_id_fk";
--> statement-breakpoint
ALTER TABLE "plugin_job_runs" DROP CONSTRAINT IF EXISTS "plugin_job_runs_company_id_companies_id_fk";
--> statement-breakpoint
ALTER TABLE "plugin_logs" DROP CONSTRAINT IF EXISTS "plugin_logs_company_id_companies_id_fk";
--> statement-breakpoint
ALTER TABLE "plugin_webhook_deliveries" DROP CONSTRAINT IF EXISTS "plugin_webhook_deliveries_company_id_companies_id_fk";
--> statement-breakpoint
ALTER TABLE "environment_custom_image_templates" DROP CONSTRAINT IF EXISTS "environment_custom_image_templates_superseded_by_template_id_fk";
--> statement-breakpoint
ALTER TABLE "environment_custom_image_templates" DROP CONSTRAINT IF EXISTS "environment_custom_image_templates_environment_id_environments_id_fk";
--> statement-breakpoint
ALTER TABLE "environment_custom_image_setup_sessions" DROP CONSTRAINT IF EXISTS "environment_custom_image_setup_sessions_template_id_fk";
--> statement-breakpoint
ALTER TABLE "environment_custom_image_setup_sessions" DROP CONSTRAINT IF EXISTS "environment_custom_image_setup_sessions_promoted_template_id_fk";
--> statement-breakpoint
ALTER TABLE "environment_custom_image_setup_sessions" DROP CONSTRAINT IF EXISTS "environment_custom_image_setup_sessions_environment_id_environments_id_fk";
--> statement-breakpoint

-- ── Drop indexes ───────────────────────────────────────────────────────
-- memory_records indexes are re-created in 0141_restore_memory_indexes.
-- All other dropped indexes are re-created below with updated definitions.
DROP INDEX IF EXISTS "memory_records_created_at_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "memory_records_embedding_hnsw_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "memory_records_company_binding_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "issues_active_task_watchdog_uq";--> statement-breakpoint
DROP INDEX IF EXISTS "issues_active_sla_monitor_alert_uq";--> statement-breakpoint
DROP INDEX IF EXISTS "pipeline_cases_lease_expires_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "pipeline_cases_parent_request_key_uq";--> statement-breakpoint
DROP INDEX IF EXISTS "knowledge_documents_company_created_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "knowledge_documents_company_updated_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "knowledge_document_revisions_document_version_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "knowledge_document_reviews_document_idx";--> statement-breakpoint

-- ── ALTER COLUMN DEFAULT re-sets ──────────────────────────────────────
-- Align column defaults with the current drizzle schema definitions.
--> statement-breakpoint
ALTER TABLE "company_skills" ALTER COLUMN "categories" SET DATA TYPE text[];--> statement-breakpoint
ALTER TABLE "company_skills" ALTER COLUMN "categories" SET DEFAULT '{}';--> statement-breakpoint
ALTER TABLE "company_skills" ALTER COLUMN "star_count" SET DEFAULT 0;--> statement-breakpoint
ALTER TABLE "company_skills" ALTER COLUMN "install_count" SET DEFAULT 0;--> statement-breakpoint
ALTER TABLE "company_skills" ALTER COLUMN "fork_count" SET DEFAULT 0;--> statement-breakpoint
ALTER TABLE "environments" ALTER COLUMN "env_vars" SET DEFAULT '{}'::jsonb;--> statement-breakpoint
ALTER TABLE "pipeline_automation_executions" ALTER COLUMN "generation" SET DEFAULT 1;--> statement-breakpoint
ALTER TABLE "routines" ALTER COLUMN "origin_kind" SET DEFAULT 'manual';--> statement-breakpoint
ALTER TABLE "company_skill_versions" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();--> statement-breakpoint
ALTER TABLE "company_skill_versions" ALTER COLUMN "file_inventory" SET DEFAULT '[]'::jsonb;--> statement-breakpoint
ALTER TABLE "company_skill_versions" ALTER COLUMN "created_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "company_skill_stars" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();--> statement-breakpoint
ALTER TABLE "company_skill_stars" ALTER COLUMN "created_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "company_skill_comments" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();--> statement-breakpoint
ALTER TABLE "company_skill_comments" ALTER COLUMN "created_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "company_skill_comments" ALTER COLUMN "updated_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "issue_watchdogs" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();--> statement-breakpoint
ALTER TABLE "issue_watchdogs" ALTER COLUMN "status" SET DEFAULT 'active';--> statement-breakpoint
ALTER TABLE "issue_watchdogs" ALTER COLUMN "trigger_count" SET DEFAULT 0;--> statement-breakpoint
ALTER TABLE "issue_watchdogs" ALTER COLUMN "created_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "issue_watchdogs" ALTER COLUMN "updated_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "external_objects" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();--> statement-breakpoint
ALTER TABLE "external_objects" ALTER COLUMN "status_category" SET DEFAULT 'unknown';--> statement-breakpoint
ALTER TABLE "external_objects" ALTER COLUMN "status_tone" SET DEFAULT 'neutral';--> statement-breakpoint
ALTER TABLE "external_objects" ALTER COLUMN "liveness" SET DEFAULT 'unknown';--> statement-breakpoint
ALTER TABLE "external_objects" ALTER COLUMN "is_terminal" SET DEFAULT false;--> statement-breakpoint
ALTER TABLE "external_objects" ALTER COLUMN "data" SET DEFAULT '{}'::jsonb;--> statement-breakpoint
ALTER TABLE "external_objects" ALTER COLUMN "created_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "external_objects" ALTER COLUMN "updated_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "external_object_mentions" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();--> statement-breakpoint
ALTER TABLE "external_object_mentions" ALTER COLUMN "confidence" SET DEFAULT 'exact';--> statement-breakpoint
ALTER TABLE "external_object_mentions" ALTER COLUMN "created_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "external_object_mentions" ALTER COLUMN "updated_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "routine_documents" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();--> statement-breakpoint
ALTER TABLE "routine_documents" ALTER COLUMN "created_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "routine_documents" ALTER COLUMN "updated_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "pipeline_case_documents" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();--> statement-breakpoint
ALTER TABLE "pipeline_case_documents" ALTER COLUMN "created_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "pipeline_case_documents" ALTER COLUMN "updated_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "environment_custom_image_templates" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();--> statement-breakpoint
ALTER TABLE "environment_custom_image_templates" ALTER COLUMN "template_kind" SET DEFAULT 'unknown';--> statement-breakpoint
ALTER TABLE "environment_custom_image_templates" ALTER COLUMN "status" SET DEFAULT 'active';--> statement-breakpoint
ALTER TABLE "environment_custom_image_templates" ALTER COLUMN "created_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "environment_custom_image_templates" ALTER COLUMN "updated_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "environment_custom_image_setup_sessions" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();--> statement-breakpoint
ALTER TABLE "environment_custom_image_setup_sessions" ALTER COLUMN "status" SET DEFAULT 'starting';--> statement-breakpoint
ALTER TABLE "environment_custom_image_setup_sessions" ALTER COLUMN "created_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "environment_custom_image_setup_sessions" ALTER COLUMN "updated_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "plan_review_gates" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();--> statement-breakpoint
ALTER TABLE "plan_review_gates" ALTER COLUMN "status" SET DEFAULT 'pending';--> statement-breakpoint
ALTER TABLE "plan_review_gates" ALTER COLUMN "acceptance_criteria" SET DEFAULT '[]'::jsonb;--> statement-breakpoint
ALTER TABLE "plan_review_gates" ALTER COLUMN "created_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "plan_review_gates" ALTER COLUMN "updated_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "memory_bindings" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();--> statement-breakpoint
ALTER TABLE "memory_bindings" ALTER COLUMN "config_json" SET DEFAULT '{}'::jsonb;--> statement-breakpoint
ALTER TABLE "memory_bindings" ALTER COLUMN "capabilities_json" SET DEFAULT '{}'::jsonb;--> statement-breakpoint
ALTER TABLE "memory_bindings" ALTER COLUMN "enabled" SET DEFAULT true;--> statement-breakpoint
ALTER TABLE "memory_bindings" ALTER COLUMN "created_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "memory_bindings" ALTER COLUMN "updated_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "memory_binding_targets" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();--> statement-breakpoint
ALTER TABLE "memory_binding_targets" ALTER COLUMN "priority" SET DEFAULT 0;--> statement-breakpoint
ALTER TABLE "memory_binding_targets" ALTER COLUMN "created_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "memory_records" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();--> statement-breakpoint
ALTER TABLE "memory_records" ALTER COLUMN "metadata_json" SET DEFAULT '{}'::jsonb;--> statement-breakpoint
ALTER TABLE "memory_records" ALTER COLUMN "importance" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "memory_records" ALTER COLUMN "created_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "memory_records" ALTER COLUMN "updated_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "memory_operations" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();--> statement-breakpoint
ALTER TABLE "memory_operations" ALTER COLUMN "scope_json" SET DEFAULT '{}'::jsonb;--> statement-breakpoint
ALTER TABLE "memory_operations" ALTER COLUMN "source_ref_json" SET DEFAULT '{}'::jsonb;--> statement-breakpoint
ALTER TABLE "memory_operations" ALTER COLUMN "usage_json" SET DEFAULT '{}'::jsonb;--> statement-breakpoint
ALTER TABLE "memory_operations" ALTER COLUMN "record_count" SET DEFAULT 0;--> statement-breakpoint
ALTER TABLE "memory_operations" ALTER COLUMN "created_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "memory_extraction_jobs" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();--> statement-breakpoint
ALTER TABLE "memory_extraction_jobs" ALTER COLUMN "status" SET DEFAULT 'queued';--> statement-breakpoint
ALTER TABLE "memory_extraction_jobs" ALTER COLUMN "submitted_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "knowledge_documents" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();--> statement-breakpoint
ALTER TABLE "knowledge_documents" ALTER COLUMN "version" SET DEFAULT 1;--> statement-breakpoint
ALTER TABLE "knowledge_documents" ALTER COLUMN "created_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "knowledge_documents" ALTER COLUMN "updated_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "knowledge_document_revisions" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();--> statement-breakpoint
ALTER TABLE "knowledge_document_revisions" ALTER COLUMN "created_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "knowledge_document_reviews" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();--> statement-breakpoint
ALTER TABLE "knowledge_document_reviews" ALTER COLUMN "created_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "knowledge_source_backlinks" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();--> statement-breakpoint
ALTER TABLE "knowledge_source_backlinks" ALTER COLUMN "created_at" SET DEFAULT now();--> statement-breakpoint

-- ── Re-add FK constraints with updated ON DELETE semantics ────────────
-- These were dropped above; the re-add applies the schema's current
-- ON DELETE specification (usually no action → cascade for plugin tables,
-- and short FK names → long descriptive names for environment tables).
-- DO blocks with pg_constraint checks make re-runs safe when the migration
-- tracker was not updated after the first successful application.
--> statement-breakpoint
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'document_revisions_company_id_companies_id_fk') THEN ALTER TABLE "document_revisions" ADD CONSTRAINT "document_revisions_company_id_companies_id_fk" FOREIGN KEY ("company_id") REFERENCES "public"."companies"("id") ON DELETE cascade ON UPDATE no action; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'documents_company_id_companies_id_fk') THEN ALTER TABLE "documents" ADD CONSTRAINT "documents_company_id_companies_id_fk" FOREIGN KEY ("company_id") REFERENCES "public"."companies"("id") ON DELETE cascade ON UPDATE no action; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'plugin_entities_company_id_companies_id_fk') THEN ALTER TABLE "plugin_entities" ADD CONSTRAINT "plugin_entities_company_id_companies_id_fk" FOREIGN KEY ("company_id") REFERENCES "public"."companies"("id") ON DELETE cascade ON UPDATE no action; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'plugin_job_runs_company_id_companies_id_fk') THEN ALTER TABLE "plugin_job_runs" ADD CONSTRAINT "plugin_job_runs_company_id_companies_id_fk" FOREIGN KEY ("company_id") REFERENCES "public"."companies"("id") ON DELETE cascade ON UPDATE no action; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'plugin_logs_company_id_companies_id_fk') THEN ALTER TABLE "plugin_logs" ADD CONSTRAINT "plugin_logs_company_id_companies_id_fk" FOREIGN KEY ("company_id") REFERENCES "public"."companies"("id") ON DELETE cascade ON UPDATE no action; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'plugin_webhook_deliveries_company_id_companies_id_fk') THEN ALTER TABLE "plugin_webhook_deliveries" ADD CONSTRAINT "plugin_webhook_deliveries_company_id_companies_id_fk" FOREIGN KEY ("company_id") REFERENCES "public"."companies"("id") ON DELETE cascade ON UPDATE no action; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'environment_custom_image_templates_superseded_by_template_id_environment_custom_image_templates_id_fk') THEN ALTER TABLE "environment_custom_image_templates" ADD CONSTRAINT "environment_custom_image_templates_superseded_by_template_id_environment_custom_image_templates_id_fk" FOREIGN KEY ("superseded_by_template_id") REFERENCES "public"."environment_custom_image_templates"("id") ON DELETE set null ON UPDATE no action; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'environment_custom_image_templates_environment_id_environments_id_fk') THEN ALTER TABLE "environment_custom_image_templates" ADD CONSTRAINT "environment_custom_image_templates_environment_id_environments_id_fk" FOREIGN KEY ("environment_id") REFERENCES "public"."environments"("id") ON DELETE cascade ON UPDATE no action; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'environment_custom_image_setup_sessions_template_id_environment_custom_image_templates_id_fk') THEN ALTER TABLE "environment_custom_image_setup_sessions" ADD CONSTRAINT "environment_custom_image_setup_sessions_template_id_environment_custom_image_templates_id_fk" FOREIGN KEY ("template_id") REFERENCES "public"."environment_custom_image_templates"("id") ON DELETE set null ON UPDATE no action; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'environment_custom_image_setup_sessions_promoted_template_id_environment_custom_image_templates_id_fk') THEN ALTER TABLE "environment_custom_image_setup_sessions" ADD CONSTRAINT "environment_custom_image_setup_sessions_promoted_template_id_environment_custom_image_templates_id_fk" FOREIGN KEY ("promoted_template_id") REFERENCES "public"."environment_custom_image_templates"("id") ON DELETE set null ON UPDATE no action; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'environment_custom_image_setup_sessions_environment_id_environments_id_fk') THEN ALTER TABLE "environment_custom_image_setup_sessions" ADD CONSTRAINT "environment_custom_image_setup_sessions_environment_id_environments_id_fk" FOREIGN KEY ("environment_id") REFERENCES "public"."environments"("id") ON DELETE cascade ON UPDATE no action; END IF; END $$;--> statement-breakpoint

-- ── Re-create indexes that were dropped above ──────────────────────────
-- These indexes are re-created with the same definitions as before.
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "issues_active_task_watchdog_uq" ON "issues" USING btree ("company_id","origin_kind","origin_id") WHERE "issues"."origin_kind" = 'task_watchdog'
          and "issues"."origin_id" is not null
          and "issues"."hidden_at" is null
          and "issues"."status" not in ('done', 'cancelled');--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "issues_active_sla_monitor_alert_uq" ON "issues" USING btree ("company_id","origin_kind","origin_fingerprint") WHERE "issues"."origin_kind" = 'sla_monitor'
          and "issues"."origin_fingerprint" <> 'default'
          and "issues"."hidden_at" is null
          and "issues"."status" not in ('done', 'cancelled');--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "pipeline_cases_lease_expires_idx" ON "pipeline_cases" USING btree ("lease_expires_at") WHERE "pipeline_cases"."lease_expires_at" is not null;--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "pipeline_cases_parent_request_key_uq" ON "pipeline_cases" USING btree ("parent_case_id","request_key") WHERE "pipeline_cases"."request_key" is not null and "pipeline_cases"."retired_at" is null;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "knowledge_documents_company_created_idx" ON "knowledge_documents" USING btree ("company_id","created_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "knowledge_documents_company_updated_idx" ON "knowledge_documents" USING btree ("company_id","updated_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "knowledge_document_revisions_document_version_idx" ON "knowledge_document_revisions" USING btree ("document_id","version");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "knowledge_document_reviews_document_idx" ON "knowledge_document_reviews" USING btree ("document_id","created_at");--> statement-breakpoint

-- ── New CHECK constraints (not previously in the migration chain) ─────
-- These CHECK constraints are defined in the current drizzle schema and
-- are genuinely new — they were never created by any earlier migration.
-- DO blocks protect against re-run when already applied.
--> statement-breakpoint
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'document_annotation_comments_exactly_one_owner_chk') THEN ALTER TABLE "document_annotation_comments" ADD CONSTRAINT "document_annotation_comments_exactly_one_owner_chk" CHECK (num_nonnulls("document_annotation_comments"."issue_id", "document_annotation_comments"."routine_id") = 1); END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'document_annotation_threads_exactly_one_owner_chk') THEN ALTER TABLE "document_annotation_threads" ADD CONSTRAINT "document_annotation_threads_exactly_one_owner_chk" CHECK (num_nonnulls("document_annotation_threads"."issue_id", "document_annotation_threads"."routine_id") = 1); END IF; END $$;