version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Chicago"
    versioning-strategy: "auto"
    commit-message:
      prefix: "deps"
      prefix-development: "deps(dev)"
      include: "scope"
    labels:
      - "dependencies"
      - "security"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "direct"
    assignees:
      - "securityengineering"
