export interface IsoControl {
  id: string;
  category: string;
  title: string;
  description: string;
  drataControlTags: string[];
}

export interface Iso27001Category {
  id: string;
  title: string;
  controls: IsoControl[];
}

export const ISO_27001_2022_ANNEX_A: Iso27001Category[] = [
  {
    id: "A.5",
    title: "Organizational controls",
    controls: [
      { id: "A.5.1", category: "A.5", title: "Policies for information security", description: "InfoSec policy and topic-specific policies approved by management, published, communicated, and reviewed at planned intervals.", drataControlTags: ["policy", "information security policy", "acceptable use"] },
      { id: "A.5.2", category: "A.5", title: "Information security roles and responsibilities", description: "Roles and responsibilities defined and allocated according to organization needs.", drataControlTags: ["roles", "responsibilities", "ISMS"] },
      { id: "A.5.3", category: "A.5", title: "Segregation of duties", description: "Conflicting duties segregated to reduce fraud or error risk.", drataControlTags: ["access control", "authorization", "privileged access"] },
      { id: "A.5.4", category: "A.5", title: "Management responsibilities", description: "Management requires personnel to apply infoSec per established policies.", drataControlTags: ["policy acknowledgment", "code of conduct"] },
      { id: "A.5.5", category: "A.5", title: "Contact with authorities", description: "Appropriate contacts with relevant authorities maintained.", drataControlTags: ["incident response", "legal"] },
      { id: "A.5.6", category: "A.5", title: "Contact with special interest groups", description: "Appropriate contacts with special interest groups or security forums.", drataControlTags: ["threat intelligence"] },
      { id: "A.5.7", category: "A.5", title: "Threat intelligence", description: "Information relating to infoSec threats collected and analyzed to produce threat intelligence.", drataControlTags: ["threat intelligence", "risk assessment"] },
      { id: "A.5.8", category: "A.5", title: "Information security in project management", description: "InfoSec integrated into project management regardless of project type.", drataControlTags: ["SDLC", "change management"] },
      { id: "A.5.9", category: "A.5", title: "Inventory of information and other associated assets", description: "Inventory of information and associated assets owned by the organization developed and maintained.", drataControlTags: ["asset inventory", "asset management"] },
      { id: "A.5.10", category: "A.5", title: "Acceptable use of information and other associated assets", description: "Rules for acceptable use and procedures for handling assets identified, documented, implemented.", drataControlTags: ["acceptable use", "asset management"] },
      { id: "A.5.11", category: "A.5", title: "Return of assets", description: "Personnel and interested parties return all assets upon termination of employment/agreement.", drataControlTags: ["offboarding", "asset management"] },
      { id: "A.5.12", category: "A.5", title: "Classification of information", description: "Information classified based on confidentiality, integrity, availability and relevant stakeholder requirements.", drataControlTags: ["data classification", "data governance"] },
      { id: "A.5.13", category: "A.5", title: "Labelling of information", description: "Appropriate set of procedures for information labelling defined and implemented.", drataControlTags: ["data classification"] },
      { id: "A.5.14", category: "A.5", title: "Information transfer", description: "Rules, procedures or agreements for information transfer in place for all types of transfer facilities.", drataControlTags: ["data transfer", "DLP"] },
      { id: "A.5.15", category: "A.5", title: "Access control", description: "Rules to control physical and logical access based on business and infoSec requirements.", drataControlTags: ["access control", "authorization", "RBAC"] },
      { id: "A.5.16", category: "A.5", title: "Identity management", description: "Full lifecycle management of identities.", drataControlTags: ["identity management", "SSO", "MFA"] },
      { id: "A.5.17", category: "A.5", title: "Authentication information", description: "Allocation and management of authentication information controlled by a formal process.", drataControlTags: ["password policy", "MFA", "authentication"] },
      { id: "A.5.18", category: "A.5", title: "Access rights", description: "Access rights provisioned, reviewed, modified, and removed per policy.", drataControlTags: ["access review", "provisioning", "deprovisioning"] },
      { id: "A.5.19", category: "A.5", title: "Information security in supplier relationships", description: "Processes and procedures defined and implemented to manage infoSec risks in supplier relationships.", drataControlTags: ["vendor", "supplier", "third party risk"] },
      { id: "A.5.20", category: "A.5", title: "Addressing information security within supplier agreements", description: "Relevant infoSec requirements established and agreed with each supplier.", drataControlTags: ["vendor security review", "contracts"] },
      { id: "A.5.21", category: "A.5", title: "Managing information security in the ICT supply chain", description: "Processes for managing infoSec risks in ICT products and services supply chain.", drataControlTags: ["supply chain", "vendor risk"] },
      { id: "A.5.22", category: "A.5", title: "Monitoring, review, and change management of supplier services", description: "Organization monitors and reviews supplier service changes.", drataControlTags: ["vendor monitoring", "change management"] },
      { id: "A.5.23", category: "A.5", title: "Information security for use of cloud services", description: "Processes for acquisition, use, management and exit from cloud services established.", drataControlTags: ["cloud security", "CASB"] },
      { id: "A.5.24", category: "A.5", title: "Information security incident management planning and preparation", description: "Organization plans and prepares for managing infoSec incidents.", drataControlTags: ["incident response", "IR plan"] },
      { id: "A.5.25", category: "A.5", title: "Assessment and decision on information security events", description: "Organization assesses infoSec events and decides if classified as incidents.", drataControlTags: ["incident response", "event monitoring"] },
      { id: "A.5.26", category: "A.5", title: "Response to information security incidents", description: "Organization responds to infoSec incidents per documented procedures.", drataControlTags: ["incident response"] },
      { id: "A.5.27", category: "A.5", title: "Learning from information security incidents", description: "Knowledge gained from incidents used to strengthen and improve controls.", drataControlTags: ["incident review", "post mortem"] },
      { id: "A.5.28", category: "A.5", title: "Collection of evidence", description: "Organization establishes procedures for identification, collection, acquisition, and preservation of evidence.", drataControlTags: ["evidence collection", "audit"] },
      { id: "A.5.29", category: "A.5", title: "Information security during disruption", description: "Organization plans how to maintain infoSec at an appropriate level during disruption.", drataControlTags: ["BCP", "DR", "business continuity"] },
      { id: "A.5.30", category: "A.5", title: "ICT readiness for business continuity", description: "ICT readiness planned, implemented, maintained, and tested based on business continuity objectives.", drataControlTags: ["DR", "backup", "business continuity"] },
      { id: "A.5.31", category: "A.5", title: "Legal, statutory, regulatory, and contractual requirements", description: "Relevant requirements identified, documented, and kept up to date.", drataControlTags: ["compliance", "legal", "regulatory"] },
      { id: "A.5.32", category: "A.5", title: "Intellectual property rights", description: "Appropriate procedures to protect intellectual property rights.", drataControlTags: ["IP", "intellectual property"] },
      { id: "A.5.33", category: "A.5", title: "Protection of records", description: "Records protected from loss, destruction, falsification, unauthorized access and release.", drataControlTags: ["records management", "retention"] },
      { id: "A.5.34", category: "A.5", title: "Privacy and protection of PII", description: "Organization identifies and meets requirements for preservation of privacy and PII protection.", drataControlTags: ["privacy", "PII", "data protection", "GDPR"] },
      { id: "A.5.35", category: "A.5", title: "Independent review of information security", description: "Organization's approach to managing infoSec and its implementation reviewed independently at planned intervals.", drataControlTags: ["audit", "internal audit", "external audit"] },
      { id: "A.5.36", category: "A.5", title: "Compliance with policies, rules, and standards for information security", description: "Compliance with org's infoSec policy, topic-specific policies, rules, and standards regularly reviewed.", drataControlTags: ["compliance", "policy review", "audit"] },
      { id: "A.5.37", category: "A.5", title: "Documented operating procedures", description: "Operating procedures for information processing facilities documented and available to personnel.", drataControlTags: ["SOP", "operating procedures"] },
    ],
  },
  {
    id: "A.6",
    title: "People controls",
    controls: [
      { id: "A.6.1", category: "A.6", title: "Screening", description: "Background verification checks on all candidates carried out per relevant laws, regulations, and ethics.", drataControlTags: ["background check", "screening", "pre-employment"] },
      { id: "A.6.2", category: "A.6", title: "Terms and conditions of employment", description: "Employment contract agreements state personnel and organization responsibilities for infoSec.", drataControlTags: ["employment agreement", "NDA", "confidentiality"] },
      { id: "A.6.3", category: "A.6", title: "Information security awareness, education, and training", description: "Personnel of organization and relevant interested parties receive appropriate infoSec awareness, education, and training.", drataControlTags: ["security training", "awareness", "education"] },
      { id: "A.6.4", category: "A.6", title: "Disciplinary process", description: "Disciplinary process formalized and communicated to take action against violators.", drataControlTags: ["disciplinary", "policy enforcement"] },
      { id: "A.6.5", category: "A.6", title: "Responsibilities after termination or change of employment", description: "InfoSec responsibilities and duties that remain valid after termination or change of employment defined, enforced, and communicated.", drataControlTags: ["offboarding", "exit process"] },
      { id: "A.6.6", category: "A.6", title: "Confidentiality or non-disclosure agreements", description: "Confidentiality or non-disclosure agreements reflecting org needs for information protection identified and regularly reviewed.", drataControlTags: ["NDA", "confidentiality agreement"] },
      { id: "A.6.7", category: "A.6", title: "Remote working", description: "Security measures to protect information accessed, processed, or stored at remote working sites implemented.", drataControlTags: ["remote work", "VPN", "endpoint security"] },
      { id: "A.6.8", category: "A.6", title: "Information security event reporting", description: "Organization provides mechanism for personnel to report observed or suspected infoSec events through appropriate channels.", drataControlTags: ["incident reporting", "whistleblowing"] },
    ],
  },
  {
    id: "A.7",
    title: "Physical controls",
    controls: [
      { id: "A.7.1", category: "A.7", title: "Physical security perimeters", description: "Security perimeters defined and used to protect areas containing information and other assets.", drataControlTags: ["physical security", "facility"] },
      { id: "A.7.2", category: "A.7", title: "Physical entry controls", description: "Secure areas protected by appropriate entry controls and access points.", drataControlTags: ["physical access", "badge system"] },
      { id: "A.7.3", category: "A.7", title: "Securing offices, rooms, and facilities", description: "Physical security for offices, rooms, and facilities designed and implemented.", drataControlTags: ["physical security", "clean desk"] },
      { id: "A.7.4", category: "A.7", title: "Physical security monitoring", description: "Premises continuously monitored for unauthorized physical access.", drataControlTags: ["physical monitoring", "CCTV", "alarm"] },
      { id: "A.7.5", category: "A.7", title: "Protecting against physical and environmental threats", description: "Protection against physical and environmental threats (fire, flood, earthquake, etc.) designed and implemented.", drataControlTags: ["environmental", "fire suppression", "disaster"] },
      { id: "A.7.6", category: "A.7", title: "Working in secure areas", description: "Security measures for working in secure areas designed and implemented.", drataControlTags: ["secure area", "visitor"] },
      { id: "A.7.7", category: "A.7", title: "Clear desk and clear screen", description: "Clear desk rules for papers and removable storage media and clear screen rules for information processing facilities.", drataControlTags: ["clean desk", "screen lock"] },
      { id: "A.7.8", category: "A.7", title: "Equipment siting and protection", description: "Equipment sited securely and protected.", drataControlTags: ["equipment", "hardware"] },
      { id: "A.7.9", category: "A.7", title: "Security of assets off-premises", description: "Off-site assets protected.", drataControlTags: ["mobile device", "remote"] },
      { id: "A.7.10", category: "A.7", title: "Storage media", description: "Storage media managed through acquisition, use, transportation, and disposal.", drataControlTags: ["media disposal", "media sanitization"] },
      { id: "A.7.11", category: "A.7", title: "Supporting utilities", description: "Information processing facilities protected from power failures and disruptions from supporting utilities.", drataControlTags: ["UPS", "power", "redundancy"] },
      { id: "A.7.12", category: "A.7", title: "Cabling security", description: "Cables carrying power, data or supporting services protected from interception, interference, or damage.", drataControlTags: ["physical", "cabling"] },
      { id: "A.7.13", category: "A.7", title: "Equipment maintenance", description: "Equipment maintained correctly to ensure availability and integrity.", drataControlTags: ["maintenance", "hardware"] },
      { id: "A.7.14", category: "A.7", title: "Secure disposal or re-use of equipment", description: "Equipment containing storage media verified to ensure sensitive data and licensed software removed or overwritten prior to disposal.", drataControlTags: ["device disposal", "data destruction"] },
    ],
  },
  {
    id: "A.8",
    title: "Technological controls",
    controls: [
      { id: "A.8.1", category: "A.8", title: "User endpoint devices", description: "Information stored on, processed by or accessible via user endpoint devices protected.", drataControlTags: ["endpoint protection", "MDM", "EDR"] },
      { id: "A.8.2", category: "A.8", title: "Privileged access rights", description: "Allocation and use of privileged access rights restricted and managed.", drataControlTags: ["privileged access", "PAM", "admin"] },
      { id: "A.8.3", category: "A.8", title: "Information access restriction", description: "Access to information and assets restricted per the access control policy.", drataControlTags: ["access control", "principle of least privilege"] },
      { id: "A.8.4", category: "A.8", title: "Access to source code", description: "Read and write access to source code, development tools, and software libraries appropriately managed.", drataControlTags: ["source code", "version control", "repository security"] },
      { id: "A.8.5", category: "A.8", title: "Secure authentication", description: "Secure authentication technologies and procedures implemented per information access restrictions.", drataControlTags: ["authentication", "SSO", "MFA", "password policy"] },
      { id: "A.8.6", category: "A.8", title: "Capacity management", description: "Use of resources monitored and adjusted in line with current and expected capacity requirements.", drataControlTags: ["capacity planning", "performance"] },
      { id: "A.8.7", category: "A.8", title: "Protection against malware", description: "Protection against malware implemented and supported by appropriate user awareness.", drataControlTags: ["antivirus", "anti-malware", "EDR"] },
      { id: "A.8.8", category: "A.8", title: "Management of technical vulnerabilities", description: "Information about technical vulnerabilities of information systems obtained, evaluated, and action taken.", drataControlTags: ["vulnerability management", "patching", "CVE"] },
      { id: "A.8.9", category: "A.8", title: "Configuration management", description: "Configurations (hardware, software, services, networks) established, documented, implemented, monitored, and reviewed.", drataControlTags: ["configuration management", "hardening", "baseline"] },
      { id: "A.8.10", category: "A.8", title: "Information deletion", description: "Information stored in information systems, devices, or any other media deleted when no longer required.", drataControlTags: ["data deletion", "retention"] },
      { id: "A.8.11", category: "A.8", title: "Data masking", description: "Data masking used in accordance with the org's policy on access control and other related topic-specific policies, and business requirements.", drataControlTags: ["data masking", "pseudonymization", "encryption"] },
      { id: "A.8.12", category: "A.8", title: "Data leakage prevention", description: "Data leakage prevention measures applied to systems, networks, and devices processing or storing sensitive information.", drataControlTags: ["DLP", "data loss prevention", "exfiltration"] },
      { id: "A.8.13", category: "A.8", title: "Information backup", description: "Backup copies of information, software and systems maintained and regularly tested per policy.", drataControlTags: ["backup", "DR", "restore testing"] },
      { id: "A.8.14", category: "A.8", title: "Redundancy of information processing facilities", description: "Information processing facilities implemented with redundancy sufficient to meet availability requirements.", drataControlTags: ["redundancy", "HA", "failover"] },
      { id: "A.8.15", category: "A.8", title: "Logging", description: "Logs recording activities, exceptions, faults and other relevant events produced, stored, protected, and analyzed.", drataControlTags: ["logging", "SIEM", "audit log"] },
      { id: "A.8.16", category: "A.8", title: "Monitoring activities", description: "Networks, systems and applications monitored for anomalous behavior and appropriate action taken.", drataControlTags: ["monitoring", "IDS", "IPS", "anomaly detection"] },
      { id: "A.8.17", category: "A.8", title: "Clock synchronization", description: "Clocks of information processing systems synchronized to approved time sources.", drataControlTags: ["NTP", "time sync"] },
      { id: "A.8.18", category: "A.8", title: "Use of privileged utility programs", description: "Use of utility programs that can override system and application controls restricted and tightly controlled.", drataControlTags: ["privileged utilities", "sudo"] },
      { id: "A.8.19", category: "A.8", title: "Installation of software on operational systems", description: "Procedures and measures to securely manage software installation on operational systems.", drataControlTags: ["software installation", "change management", "approved software"] },
      { id: "A.8.20", category: "A.8", title: "Networks security", description: "Networks and network devices secured, managed, and controlled.", drataControlTags: ["network security", "firewall", "segmentation"] },
      { id: "A.8.21", category: "A.8", title: "Security of network services", description: "Security mechanisms, service levels, and service requirements of network services identified, implemented, and monitored.", drataControlTags: ["network services", "SLA"] },
      { id: "A.8.22", category: "A.8", title: "Segregation of networks", description: "Groups of information services, users, and information systems segregated on networks.", drataControlTags: ["network segmentation", "VLAN", "firewall"] },
      { id: "A.8.23", category: "A.8", title: "Web filtering", description: "Access to external websites managed to reduce exposure to malicious content.", drataControlTags: ["web filtering", "content filtering", "DNS filtering"] },
      { id: "A.8.24", category: "A.8", title: "Use of cryptography", description: "Rules for effective use of cryptography, including cryptographic key management, defined and implemented.", drataControlTags: ["encryption", "cryptography", "key management", "TLS"] },
      { id: "A.8.25", category: "A.8", title: "Secure development life cycle", description: "Rules for secure development of software and systems established and applied.", drataControlTags: ["SDLC", "secure coding", "SAST", "DAST"] },
      { id: "A.8.26", category: "A.8", title: "Application security requirements", description: "InfoSec requirements identified, specified, and approved when developing or acquiring applications.", drataControlTags: ["application security", "security requirements"] },
      { id: "A.8.27", category: "A.8", title: "Secure system architecture and engineering principles", description: "Principles for engineering secure systems established, documented, maintained, and applied.", drataControlTags: ["security architecture", "design review", "threat modeling"] },
      { id: "A.8.28", category: "A.8", title: "Secure coding", description: "Secure coding principles applied to software development.", drataControlTags: ["secure coding", "code review", "SAST"] },
      { id: "A.8.29", category: "A.8", title: "Security testing in development and acceptance", description: "Security testing processes defined and implemented in the development life cycle.", drataControlTags: ["security testing", "penetration testing", "DAST"] },
      { id: "A.8.30", category: "A.8", title: "Outsourced development", description: "Organization directs, monitors, and reviews outsourced system development activities.", drataControlTags: ["outsourced development", "vendor management", "SDLC"] },
      { id: "A.8.31", category: "A.8", title: "Separation of development, test, and production environments", description: "Development, testing, and production environments separated and secured.", drataControlTags: ["environment separation", "test data"] },
      { id: "A.8.32", category: "A.8", title: "Change management", description: "Changes to information processing facilities and information systems subject to change management procedures.", drataControlTags: ["change management", "change control"] },
      { id: "A.8.33", category: "A.8", title: "Test information", description: "Test information appropriately selected, protected, and managed.", drataControlTags: ["test data", "data protection", "sanitization"] },
      { id: "A.8.34", category: "A.8", title: "Protection of information systems during audit testing", description: "Audit tests and other assurance activities involving assessment of operational systems planned and agreed.", drataControlTags: ["audit", "assessment"] },
    ],
  },
];