import { PostHog } from "posthog-node";
import type { FeatureFlagEvaluations } from "posthog-node";
import { logger } from "../middleware/logger.js";
import { POSTHOG_FLUSH_INTERVAL_MS } from "../timeout-constants.js";
import { redactSensitiveText } from "../redaction.js";

let client: PostHog | null = null;
let _initialized = false;

/**
 * Initialize (or re-initialize) the PostHog client from environment variables.
 *
 * Reads `POSTHOG_API_KEY` and `POSTHOG_HOST` from the environment.
 * No-op when either is absent — the server boots cleanly without PostHog.
 *
 * Safe to call multiple times — returns the existing singleton client.
 * Exported mainly for testing and explicit server-start sequencing.
 */
export function initPostHog(): PostHog | null {
  if (_initialized) return client;
  _initialized = true;

  const apiKey = process.env.POSTHOG_API_KEY;
  const host = process.env.POSTHOG_HOST;

  if (!apiKey || !host) {
    client = null;
    return null;
  }

  try {
    client = new PostHog(apiKey, {
      host,
      flushAt: 20,
      flushInterval: POSTHOG_FLUSH_INTERVAL_MS,
    });
    logger.info({ host }, "[paperclip] PostHog instrumentation enabled");
  } catch (err) {
    logger.warn(
      { err },
      "[paperclip] Failed to initialize PostHog client; continuing without PostHog",
    );
    client = null;
  }

  return client;
}

/** @returns the singleton PostHog client, or null if not configured. */
function getClient(): PostHog | null {
  if (!_initialized) return initPostHog();
  return client;
}

/**
 * Returns true when the PostHog client is active (env vars were present and
 * initialisation succeeded).
 */
export function isPostHogEnabled(): boolean {
  return getClient() !== null;
}

/**
 * Capture a server-side error event via PostHog's `captureException`.
 *
 * Automatically attaches the error's name, message, and stack trace as
 * `$exception_*` properties in PostHog. Any additional properties in `extra`
 * are merged into the event properties.
 *
 * **Security:** Error messages and stack traces are scrubbed through
 * `redactSensitiveText()` before being sent to PostHog to prevent PII
 * (file paths, SQL constraint values, connection strings) from egressing
 * to a third-party telemetry service. Only the error name/code is passed
 * through unchanged.
 *
 * **Caller contract:** This function operates on a **clone** of the error
 * object. Any code that reads `error.message` or `error.stack` **after**
 * calling this function will see the original, unredacted values. If you
 * need the redacted version, capture it from the sanitized clone before it
 * goes out of scope. (This is the inverse of the pattern in
 * `error-handler.ts`, where the HTTP response message is snapshotted
 * *before* calling `captureErrorEvent`.)
 *
 * No-op when PostHog is not configured.
 */
export function captureErrorEvent(
  error: unknown,
  distinctId?: string,
  extra?: Record<string | number, unknown>,
): void {
  const c = getClient();
  if (!c) return;

  // Strip PII before egress to third-party telemetry.
  // Operate on a clone so the original error object is NOT mutated —
  // any subsequent code reading the original (e.g. logger.error with
  // the error as structured data) will see the unredacted values.
  const sanitized = sanitizeErrorForTelemetry(error);
  c.captureException(sanitized, distinctId ?? "paperclip-server", extra);
}

/**
 * Clone an Error (including its cause chain) so telemetry sanitization
 * never mutates the caller's original error object.
 *
 * Uses the error's own prototype so `instanceof` checks and custom error
 * classes survive the copy. `message` is an own data property on Error
 * instances; `stack` is lazily generated by V8 (getter on Error.prototype),
 * so it is read from the original first (harmless — any code that later
 * logs the error does the same) and copied as an own property.
 */
function cloneError(error: Error): Error {
  const clone = Object.create(Object.getPrototypeOf(error)) as Error;
  clone.message = error.message;
  clone.stack = error.stack;
  // Copy any remaining own properties (cause, code, custom fields).
  for (const key of Object.getOwnPropertyNames(error)) {
    if (key !== "message" && key !== "stack") {
      (clone as any)[key] = (error as any)[key];
    }
  }
  return clone;
}

/**
 * Strip PII from an error before sending to a third-party telemetry service.
 *
 * - Error name / constructor name: passed through (low-risk identifiers).
 * - Error message: redacted via `redactSensitiveText()` to catch secrets,
 *   file paths, emails, and connection strings that may appear in messages
 *   (e.g. SQL constraint violation messages containing user email).
 * - Stack trace: redacted. PostHog's `captureException` auto-extracts
 *   `$exception_stack_trace` from the error object; preserving the trace
 *   (with redacted file paths and tokens) enables triage by throw site.
 * - Non-standard Error objects: returned as-is (the caller is responsible).
 *
 * **Mutation contract:** operates on a clone of the error and its cause
 * chain — the caller's error object is never modified. If you need the
 * redacted values (e.g. for a response body), use the returned clone.
 */
function sanitizeErrorForTelemetry(error: unknown): Error | unknown {
  if (!(error instanceof Error)) return error;

  const clone = cloneError(error);
  clone.message = redactSensitiveText(clone.message);

  if (typeof clone.stack === "string") {
    clone.stack = redactSensitiveText(clone.stack);
  }

  // Recursively redact the cause chain (cloning in place preserves identity
  // of the returned error while never touching the original objects).
  if (clone.cause instanceof Error) {
    clone.cause = sanitizeErrorForTelemetry(clone.cause);
  }

  return clone;
}

/**
 * Capture a custom metric / business event in PostHog.
 *
 * **IMPORTANT:** Always pass a meaningful `distinctId` (typically `companyId`)
 * for business events. The default `"paperclip-server"` collapses all companies
 * and actors into a single anonymous user, making per-company analytics
 * impossible. Pass the actor identity in `properties` as well.
 *
 * @param eventName  The PostHog event name (e.g. `"agent.run.completed"`).
 * @param distinctId  User or actor identifier. **Do not rely on the default.**
 *   Pass `companyId` for business events.
 * @param properties  Arbitrary properties to attach (metric name, value, tags, …).
 *
 * No-op when PostHog is not configured.
 */
export function captureMetric(
  eventName: string,
  distinctId?: string,
  properties?: Record<string | number, unknown>,
): void {
  const c = getClient();
  if (!c) return;
  c.capture({
    distinctId: distinctId ?? "paperclip-server",
    event: eventName,
    properties: properties ?? {},
  });
}

/**
 * Flush pending PostHog events to the server.
 * Returns immediately when PostHog is not configured.
 */
export async function flush(): Promise<void> {
  const c = getClient();
  if (!c) return;
  await c.flush();
}

/**
 * Shut down the PostHog client — flushes pending events and releases resources.
 * No-op when PostHog is not configured. Idempotent.
 */
export async function shutdownPostHog(): Promise<void> {
  const c = getClient();
  if (!c) return;
  await c.shutdown();
  client = null;
  _initialized = false;
}
