#!/bin/bash
# GCP Evidence Auto-Collection Script for Aira ISO 27001 A.8 Controls
# Generated by Aira evidence module
# Requires: gcloud CLI authenticated with appropriate IAM roles
# Usage: bash scripts/collect-gcp-evidence.sh [PROJECT_ID]

PROJECT_ID="${1:-$(gcloud config get-value project)}"
ORG_ID="${2:-}"
OUTPUT_DIR="data/evidence"

mkdir -p "$OUTPUT_DIR"

echo "=== Collecting GCP IAM Evidence for A.8.2, A.8.3, A.8.5 ==="
# Organization-level IAM (if ORG_ID provided)
[ -n "$ORG_ID" ] && gcloud organizations get-iam-policy "$ORG_ID" --format=json > "$OUTPUT_DIR/gcp-iam-org.json" 2>/dev/null || echo "ORG_ID not provided, skipping org-level IAM"
# Project-level IAM
gcloud projects get-iam-policy "$PROJECT_ID" --format=json > "$OUTPUT_DIR/gcp-iam-project.json"
# IAM service accounts
gcloud iam service-accounts list --format=json > "$OUTPUT_DIR/gcp-iam-service-accounts.json"
# IAM roles (custom)
gcloud iam roles list --format=json > "$OUTPUT_DIR/gcp-iam-custom-roles.json" 2>/dev/null || echo "No custom roles or permission denied"

echo "=== Collecting GCP Infrastructure Evidence for A.8.6-A.8.14 ==="
# Security Command Center findings
gcloud scc findings list "$ORG_ID" --format=json > "$OUTPUT_DIR/gcp-scc-findings.json" 2>/dev/null || echo "SCC requires organization-level access"
# Compute Engine instances (OS config, metadata)
gcloud compute instances list --format=json > "$OUTPUT_DIR/gcp-compute-instances.json"
# Cloud KMS key rings
gcloud kms keyrings list --location=global --format=json > "$OUTPUT_DIR/gcp-kms-keyrings.json" 2>/dev/null || echo "No KMS resources"
# Cloud Storage bucket config (retention, encryption)
gcloud storage buckets list --format=json > "$OUTPUT_DIR/gcp-storage-buckets.json" 2>/dev/null || echo "No storage buckets or permission denied"
# Backup/redundancy config
gcloud compute snapshots list --format=json > "$OUTPUT_DIR/gcp-compute-snapshots.json" 2>/dev/null || echo "No snapshots"
gcloud compute disks list --format=json > "$OUTPUT_DIR/gcp-compute-disks.json"
# DLP API config
gcloud alpha dlp inspect-templates list --format=json > "$OUTPUT_DIR/gcp-dlp-inspect-templates.json" 2>/dev/null || echo "DLP API not enabled"
# VPC Service Controls
gcloud access-context-manager perimeters list --format=json > "$OUTPUT_DIR/gcp-vpc-sc.json" 2>/dev/null || echo "Access Context Manager not enabled"

echo "=== Collecting GCP Observability Evidence for A.8.15-A.8.17 ==="
# Cloud Logging sinks
gcloud logging sinks list --format=json > "$OUTPUT_DIR/gcp-logging-sinks.json"
# Monitoring alert policies
gcloud alpha monitoring policies list --format=json > "$OUTPUT_DIR/gcp-monitoring-policies.json" 2>/dev/null || echo "Monitoring API not enabled or permission denied"
# Monitoring notification channels
gcloud alpha monitoring channels list --format=json > "$OUTPUT_DIR/gcp-monitoring-channels.json" 2>/dev/null || echo "No notification channels"
# Audit log config
gcloud logging logs list --format=json > "$OUTPUT_DIR/gcp-logging-logs.json"

echo "=== Collecting GCP Network Evidence for A.8.20-A.8.24 ==="
# VPC networks
gcloud compute networks list --format=json > "$OUTPUT_DIR/gcp-networks.json"
# Firewall rules
gcloud compute firewall-rules list --format=json > "$OUTPUT_DIR/gcp-firewall-rules.json"
# SSL policies
gcloud compute ssl-policies list --format=json > "$OUTPUT_DIR/gcp-ssl-policies.json" 2>/dev/null || echo "No SSL policies"
# Cloud DNS
gcloud dns managed-zones list --format=json > "$OUTPUT_DIR/gcp-dns-zones.json" 2>/dev/null || echo "No managed zones"
# Cloud Armor
gcloud compute security-policies list --format=json > "$OUTPUT_DIR/gcp-cloud-armor.json" 2>/dev/null || echo "No Cloud Armor policies"

echo "=== Collecting GCP Operations Evidence for A.8.18-A.8.19 ==="
# OS Login config
gcloud compute project-info describe --format=json | jq '.commonInstanceMetadata.items[] | select(.key=="enable-oslogin" or .key=="enable-oslogin-2fa")' > "$OUTPUT_DIR/gcp-os-login.json" 2>/dev/null || echo "Cannot read project metadata"
# Guest policy / software inventory
gcloud compute instances os-inventory list-instances --format=json > "$OUTPUT_DIR/gcp-os-inventory.json" 2>/dev/null || echo "OS Inventory not enabled"

echo "=== Evidence collection complete ==="
echo "Output directory: $OUTPUT_DIR"
ls -la "$OUTPUT_DIR"

echo "Next: run 'npm run evidence:manifest' to generate the evidence manifest"